CREATE DATABASE CDW_SAPP;
USE CDW_SAPP;

CREATE TABLE `CDW_SAPP_BRANCH` (
  `BRANCH_CODE` int(9) NOT NULL,
  `BRANCH_NAME` varchar(25) DEFAULT NULL,
  `BRANCH_STREET` varchar(30) DEFAULT NULL,
  `BRANCH_CITY` varchar(30) NOT NULL,
  `BRANCH_STATE` varchar(30) DEFAULT NULL,
  `BRANCH_ZIP` int(7) DEFAULT NULL,
  `BRANCH_PHONE` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`BRANCH_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CDW_SAPP_CUSTOMER` (
  `FIRST_NAME` varchar(40) NOT NULL,
  `MIDDLE_NAME` varchar(40) DEFAULT NULL,
  `LAST_NAME` varchar(40) DEFAULT NULL,
  `SSN` int(9) NOT NULL,
  `CREDIT_CARD_NO` varchar(16) NOT NULL DEFAULT '',
  `APT_NO` varchar(7) DEFAULT NULL,
  `STREET_NAME` varchar(30) DEFAULT NULL,
  `CUST_CITY` varchar(30) NOT NULL,
  `CUST_STATE` varchar(30) DEFAULT NULL,
  `CUST_COUNTRY` varchar(30) DEFAULT NULL,
  `CUST_ZIP` varchar(7) DEFAULT NULL,
  `CUST_PHONE` int(10) DEFAULT NULL,
  `CUST_EMAIL` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`CREDIT_CARD_NO`,`SSN`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `CDW_SAPP_CREDITCARD` (
  `TRANSACTION_ID` int(9) NOT NULL,
  `DAY` int(2) NOT NULL,
  `MONTH` int(2) DEFAULT NULL,
  `YEAR` int(4) DEFAULT NULL,
  `CREDIT_CARD_NO` varchar(16) DEFAULT NULL,
  `CUST_SSN` int(9) DEFAULT NULL,
  `BRANCH_CODE` int(9) DEFAULT NULL,
  `TRANSACTION_TYPE` varchar(30) DEFAULT NULL,
  `TRANSACTION_VALUE` decimal(20,3) DEFAULT NULL,
  PRIMARY KEY (`TRANSACTION_ID`),
  KEY `FK_CARDCUST` (`CREDIT_CARD_NO`,`CUST_SSN`),
  KEY `FK_CARDBRANCH` (`BRANCH_CODE`),
  CONSTRAINT `FK_CARDBRANCH` FOREIGN KEY (`BRANCH_CODE`) REFERENCES `CDW_SAPP_BRANCH` (`BRANCH_CODE`),
  CONSTRAINT `FK_CARDCUST` FOREIGN KEY (`CREDIT_CARD_NO`, `CUST_SSN`) REFERENCES `CDW_SAPP_CUSTOMER` (`CREDIT_CARD_NO`, `SSN`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
